

```{r Clear screen and set cd }
# Initial clean-up
if(!is.null(dev.list())) dev.off()
cat("\014")
rm(list = ls(all=TRUE)) 


```

```{r Libraries}
library(MASS)
library(rcompanion)

```


#Omitted variables bias

$$
\text{ DGP:} \quad y_{i} = \beta_{0}+\beta_{1}x_{1i}+\beta_{2}x_{2i}+\varepsilon_{i} \\
\varepsilon_{i} \sim iidN(0,1) \\ 

\left[\begin{array}{l}
x_{1} \\
x_{2}
\end{array}\right] \sim N\left[\left(\begin{array}{l}
0.5 \\
0.5
\end{array}\right),\left(\begin{array}{cc}
1 & \sigma_{12} \\
\sigma_{12} & 1
\end{array}\right)\right]

\\
\text{Estimated Model:} \quad y_{i} = \alpha_{0}+\alpha_{1}x_{1i}+v_{i} \\
$$


```{r Omitted Variabel  - Biased estimator}


# Define the population parameters
beta0 = 10
beta1 = 1
beta2 = 1.5

# Sample size
n = 100

#Number of replications
replication = 5000


sigma12 = 0.3 

alfahat0 = rep(0,replication)
alfahat1 = rep(0,replication)
x = mvrnorm(n, mu = c(0.5,0.5), Sigma=matrix(c(1,sigma12,sigma12,1),2,2), empirical = TRUE)

x1 = x[,1]
x2 = x[,2]

for (i in (1:replication)) {

epsilon = rnorm(n, mean = 0, sd = 1) 

# DGP
y = beta0 + beta1 * x1 + beta2 * x2 + epsilon
  
# Estimated Model 
model = lm(y ~ x1)
  
alfahat0[i] = summary.lm(model)$coefficients[1,1]
alfahat1[i] = summary.lm(model)$coefficients[2,1]

}

bias_alfa0 = (mean(alfahat0) - beta0)*100
bias_alfa1 = (mean(alfahat1) - beta1)*100

bias_alfa0
bias_alfa1

plotNormalHistogram(alfahat1, prob = TRUE, col="light coral",linecol="blue",border="red",
                    xlim=c(0.8,2), 
                    main = "Sampling Distributions of Beta Estimates-Biased estimator", 
                    xlab="Estimates")
abline(v = 1, col="blue", lwd=3, lty=2)

```


    
```{r Omitted Variabel  - Inonsistent Estimator}

# Define the population parameters
beta0   = 10
beta1   = 1
beta2   = 1.5


sigma12     = 0.3

replication = 2000

epsilon =  0.05 #Any arbitrarily small positive number


n_all = seq(100, 10000, by = 900) #Sample Sizes

prob1 = rep(0, length(n_all))
prob2 = rep(0, length(n_all))

for (i in (1:length(n_all))) {
  
n = n_all[i]

alfahat0 = rep(0,replication)
alfahat1 = rep(0,replication)

x = mvrnorm(n, mu = c(0.5,0.5), Sigma = matrix(c(1,sigma12,sigma12,1),2,2), empirical = TRUE)

x1 = x[,1]
x2 = x[,2]

for (j in (1:replication)) {

error_term = rnorm(n, mean = 0, sd = 1) 
  
# Data Generating Process
y = beta0 + beta1 * x1 + beta2 * x2 + error_term
    
# Estimated Model 
model = lm(y ~ x1)

alfahat0[j] = summary.lm(model)$coefficients[1,1]
alfahat1[j] = summary.lm(model)$coefficients[2,1]
    
}
  
prob1[i] = mean(abs(alfahat0 - beta0) < epsilon)
prob2[i] = mean(abs(alfahat1 - beta1) < epsilon)
  
}

prob1
prob2

x = seq(100,10000, 900)
plot(y = prob2, x, ylim=c(0,1) ,xlim=c(100,10000), pch=19,
     main="Inconsistent estimator", xlab="Sample size" ,
     ylab="Probability ")

```

